language: go

go:
 - 1.9
 - tip

install:
  - go get github.com/sirupsen/logrus
  - go get github.com/smartystreets/goconvey

script:
  - go test ./... -v

aftter_success:
  - curl http://gocover.io/github.com/deluan/rest > /dev/null

notifications:
  email:
    - travis@deluan.com