language: go

go:
 - 1.9
 - tip

install:
  - go get github.com/sirupsen/logrus
  - go get github.com/smartystreets/goconvey

script:
  - go test ./... -v

notifications:
  email:
    - travis@deluan.com