name: CI
on: [push]
jobs:

  build:
    name: Test on ${{ matrix.os }} (Go ${{ matrix.go }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        go: [stable]
        include:
          # Minimum version from go.mod.
          - os: ubuntu-latest
            go: "1.19"

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}

    - name: Test
      run: go test -cover ./... -v
