name: CI
on: [push]
jobs:

  build:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Set up Go 1.19
        uses: actions/setup-go@v5
        with:
          go-version: '1.19'

      - name: Test
        run: go test -cover ./... -v
